---
- hosts: all
  become: true

  tasks:
    - name: install apache and php
      package:
        name:
          - apache2
          - php
        update_cache: yes
        state: latest
      # when: ansible_distribution == ["Debian", "Ubuntu"]
